library(tidyverse)
library(jsonlite)
library(dplyr)
library(sf)
library(ggplot2)
library(RColorBrewer)
library(data.table)

#setwd("C:/Users/Ronan/Documents/GitHub/Projet_Tutore/Script")
#setwd("/Users/waldislav/Fac/Cours/M2/Projet\ Tutorés/Projet_Tutore/Script")
#setwd("C://Users/ronan/Documents/Cours/Projet_Tutore-main/Projet_Tutore-main/Script")

france <- fread("Data/reglementations/france.csv")
france_conformite <- fread("Data/reglementations/france_conformite.csv")
france_norme <- fread("Data/reglementations/france_norme.csv")
groupe_annee <- fread("Data/reglementations/groupe_annee.csv")
matrix_france <- fread("Data/reglementations/matrix_france.csv")
pfas <- fread("Data/reglementations/pfas.csv")
pfas_group <- fread("Data/reglementations/pfas_group.csv")
pfas_group_filtre <- fread("Data/reglementations/pfas_group_filtre.csv")
producteur <- fread("Data/reglementations/producteur.csv")
regions <- st_read("regions.gpkg")
regions_by_year <- fread("Data/reglementations/regions_by_year.csv")
regions_sum_pfas <- fread("Data/reglementations/regions_sum_pfas.csv")
resultats <- fread("Data/reglementations/resultats.csv")
resultat_conformite_matrix <- fread("Data/reglementations/resultat_conformite_matrix.csv")
resultats_region <- fread("Data/reglementations/resultats_region.csv")
resultats_region_annee <- fread("Data/reglementations/resultats_region_annee.csv")
user <- fread("Data/reglementations/user.csv")
year_counts <- fread("Data/reglementations/year_counts.csv")
pfas_group_filtre$substance <- factor(pfas_group_filtre$substance, 
                                      levels = unique(pfas_group_filtre$substance))
source("Script/Charge_data/stat_region.R")
