library(tidyverse)
library(jsonlite)
library(dplyr)
library(sf)
library(ggplot2)
library(RColorBrewer)
library(data.table)

#setwd("C:/Users/Ronan/Documents/GitHub/Projet_Tutore/Script")
#setwd("/Users/waldislav/Fac/Cours/M2/Projet\ Tutorés/Projet_Tutore/Script")
france <- fread("Data/calcul/france.csv")
france_norme <- fread("Data/calcul/france_norme.csv")
groupe_annee <- fread("Data/calcul/groupe_annee.csv")
matrix_france <- fread("Data/calcul/matrix_france.csv")
pfas <- fread("Data/calcul/pfas.csv")
pfas_group <- fread("Data/calcul/pfas_group.csv")
pfas_group_filtre <- fread("Data/calcul/pfas_group_filtre.csv")
producteur <- fread("Data/calcul/producteur.csv")
regions <- st_read("regions.gpkg")
regions_by_year <- fread("Data/calcul/regions_by_year.csv")
regions_sum_pfas <- fread("Data/calcul/regions_sum_pfas.csv")
resultats <- fread("Data/calcul/resultats.csv")
resultat_conformite_matrix <- fread("Data/calcul/resultat_conformite_matrix.csv")
resultats_region <- fread("Data/calcul/resultats_region.csv")
resultats_region_annee <- fread("Data/calcul/resultats_region_annee.csv")
user <- fread("Data/calcul/user.csv")
year_counts <- fread("Data/calcul/year_counts.csv")
pfas_group_filtre$substance <- factor(pfas_group_filtre$substance, 
                                      levels = unique(pfas_group_filtre$substance))
moyenne_globale <- fread("Data/calcul/moyenne_globale.csv")
source("Script/Charge_data/stat_region.R")
