library(tidyverse)
library(jsonlite)
library(dplyr)
library(sf)
library(ggplot2)
library(RColorBrewer)

setwd("C:/Users/Ronan/Documents/GitHub/Projet_Tutore/Script")
#setwd("/Users/waldislav/Fac/Cours/M2/Projet\ Tutorés/Projet_Tutore/Script")
#setwd("C://Users/ronan/Documents/Cours/Projet_Tutore-main/Projet_Tutore-main/Script")

france <- read_csv("../Data/reglementations/france.csv")
france_conformite <- read_csv("../Data/reglementations/france_conformite.csv")
france_norme <- read_csv("../Data/reglementations/france_norme.csv")
groupe_annee <- read_csv("../Data/reglementations/groupe_annee.csv")
matrix_france <- read_csv("../Data/reglementations/matrix_france.csv")
pfas <- read_csv("../Data/reglementations/pfas.csv")
pfas_group <- read_csv("../Data/reglementations/pfas_group.csv")
pfas_group_filtre <- read_csv("../Data/reglementations/pfas_group_filtre.csv")
producteur <- read_csv("../Data/reglementations/producteur.csv")
regions <- st_read("../regions.gpkg")
regions_by_year <- read_csv("../Data/reglementations/regions_by_year.csv")
regions_sum_pfas <- read_csv("../Data/reglementations/regions_sum_pfas.csv")
resultats <- read_csv("../Data/reglementations/resultats.csv")
resultats_conformite_matrix <- read_csv("../Data/reglementations/resultats_conformite_matrix.csv")
resultats_region <- read_csv("../Data/reglementations/resultats_region.csv")
resultats_region_annee <- read_csv("../Data/reglementations/resultats_region_annee.csv")
user <- read_csv("../Data/reglementations/user.csv")
year_counts <- read_csv("../Data/reglementations/year_counts.csv")